file_path: "../policy/SPARQ/SPARQ/"
runner_type: "onnx"


num_joint: 12

joint_idx_style: "isaaclab_to_rainbow"
joint_idx_conversion_isaaclab_to_rainbow:
  input: [0, 3, 6, 9, 1, 4, 7, 10, 2, 5, 8, 11]
  output: [0, 4, 8, 1, 5, 9, 2, 6, 10, 3, 7, 11]


default_joint_angle:
  - 0.0
  - 0.7
  - -1.4
  - 0.0
  - 0.7
  - -1.4
  - 0.0
  - 0.7
  - -1.4
  - 0.0
  - 0.7
  - -1.4


action_scale : 0.25
action_clip : 10

history_length : 0

obs_type : 0
